app/src/Entity/Note.php
<?php

namespace App\Entity;

use App\Repository\NoteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=NoteRepository::class)
 */
class Note
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(
     *     targetEntity=Category::class,
     *     inversedBy="notes"
     * )
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\ManyToMany(
     *     targetEntity=Tag::class,
     *      inversedBy="notes")
     */
    private $tags;

    /**
     * Author.
     *
     * @var \App\Entity\User
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    /**
     * @return $this
     */
    public function setCreatedAt(\DateTimeInterface $created_at): void
    {
        $this->created_at = $created_at;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }
}

app/src/Form/NoteType.php
<?php
/**
 * Note type.
 */

namespace App\Form;

use App\Entity\Category;
use App\Entity\Note;
use App\Form\DataTransformer\TagsDataTransformer;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class NoteType.
 */
class NoteType extends AbstractType
{
    /**
     * Tags data transformer.
     *
     * @var \App\Form\DataTransformer\TagsDataTransformer
     */
    private $tagsDataTransformer;

    /**
     * TaskType constructor.
     *
     * @param \App\Form\DataTransformer\TagsDataTransformer $tagsDataTransformer Tags data transformer
     */
    public function __construct(TagsDataTransformer $tagsDataTransformer)
    {
        $this->tagsDataTransformer = $tagsDataTransformer;
    }

    /**
     * Builds the form.
     *
     * This method is called for each type in the hierarchy starting from the
     * top most type. Type extensions can further modify the form.
     *
     * @see FormTypeExtensionInterface::buildForm()
     *
     * @param \Symfony\Component\Form\FormBuilderInterface $builder The form builder
     * @param array                                        $options The options
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add(
            'title',
            TextType::class,
            [
                'label' => 'label_title',
                'required' => true,
                'attr' => ['max_length' => 64],
            ]
        );
        $builder->add(
            'content',
            TextType::class,
            [
                'label' => 'label_content',
                'required' => true,
            ]
        );
        $builder->add(
            'category',
            EntityType::class,
            [
                'class' => Category::class,
                'choice_label' => function ($category) {
                    return $category->getTitle();
                },
                'label' => 'label_category',
                'placeholder' => 'label_none',
                'required' => true,
            ]
        );
        $builder->add(
            'tags',
            TextType::class,
            [
                'label' => 'label_tag',
                'required' => false,
                'attr' => ['max_length' => 128],
            ]
        );
        $builder->get('tags')->addModelTransformer(
            $this->tagsDataTransformer
        );
    }

    /**
     * Configures the options for this type.
     *
     * @param \Symfony\Component\OptionsResolver\OptionsResolver $resolver The resolver for the options
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults(['data_class' => Note::class]);
    }

    /**
     * Returns the prefix of the template block name for this type.
     *
     * The block prefix defaults to the underscored short class name with
     * the "Type" suffix removed (e.g. "UserProfileType" => "user_profile").
     *
     * @return string The prefix of the template block name
     */
    public function getBlockPrefix(): string
    {
        return 'note';
    }
}

app/src/Controller/NoteController.php
<?php
/**
 * Note controller.
 */

namespace App\Controller;

use App\Entity\Note;
use App\Form\NoteType;
use App\Service\NoteService;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class NoteController.
 *
 * @Route("/note")
 */
class NoteController extends AbstractController
{
    /**
     * Note service.
     *
     * @var \App\Service\NoteService
     */
    private $noteService;

    /**
     * NoteController constructor.
     *
     * @param \App\Service\NoteService $noteService Note service
     */
    public function __construct(NoteService $noteService)
    {
        $this->noteService = $noteService;
    }

    /**
     * Index action.
     *
     * @param \Symfony\Component\HttpFoundation\Request $request HTTP request
     *
     * @return \Symfony\Component\HttpFoundation\Response HTTP response
     *
     * @Route(
     *     "/",
     *     name="note_index",
     * )
     */
    public function index(Request $request): Response
    {
        $pagination = $this->noteService->createPaginatedList(
            $request->query->getInt('page', 1),
            $this->getUser(),
            $request->query->getAlnum('filters', [])
        );

        return $this->render(
            'note/index.html.twig',
            ['pagination' => $pagination]
        );
    }

    /**
     * Show action.
     *
     * @param \App\Entity\Note $note Note entity
     *
     * @return \Symfony\Component\HttpFoundation\Response HTTP response
     *
     * @Route(
     *     "/{id}",
     *     methods={"GET"},
     *     name="note_show",
     *     requirements={"id": "[1-9]\d*"},
     * )
     *
     * @Security(
     *     "is_granted('ROLE_ADMIN') or is_granted('VIEW', note)"
     * )
     */
    public function show(Note $note): Response
    {
        return $this->render(
            'note/show.html.twig',
            ['note' => $note]
        );
    }

    /**
     * Create action.
     *
     * @param \Symfony\Component\HttpFoundation\Request $request HTTP request
     *
     * @return \Symfony\Component\HttpFoundation\Response HTTP response
     *
     * @throws \Doctrine\ORM\ORMException
     * @throws \Doctrine\ORM\OptimisticLockException
     *
     * @Route(
     *     "/create",
     *     methods={"GET", "POST"},
     *     name="note_create",
     * )
     */
    public function create(Request $request): Response
    {
        $note = new Note();
        $form = $this->createForm(NoteType::class, $note);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $note->setAuthor($this->getUser());
            $note->setUpdatedAt(new \DateTime());
            $note->setCreatedAt(new \DateTime());
            $this->noteService->save($note);
            $this->addFlash('success', 'message_created_successfully');

            return $this->redirectToRoute('note_index');
        }

        return $this->render(
            'note/create.html.twig',
            ['form' => $form->createView()]
        );
    }

    /**
     * Edit action.
     *
     * @param \Symfony\Component\HttpFoundation\Request $request HTTP request
     * @param \App\Entity\Note                          $note    Note entity
     *
     * @return \Symfony\Component\HttpFoundation\Response HTTP response
     *
     * @throws \Doctrine\ORM\ORMException
     * @throws \Doctrine\ORM\OptimisticLockException
     *
     * @Route(
     *     "/{id}/edit",
     *     methods={"GET", "PUT"},
     *     requirements={"id": "[1-9]\d*"},
     *     name="note_edit",
     * )
     *
     * @Security(
     *     "is_granted('ROLE_ADMIN') or is_granted('EDIT', note)"
     * )
     */
    public function edit(Request $request, Note $note): Response
    {
        $form = $this->createForm(NoteType::class, $note, ['method' => 'PUT']);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->noteService->save($note);
            $this->addFlash('success', 'message_updated_successfully');

            return $this->redirectToRoute('note_index');
        }

        return $this->render(
            'note/edit.html.twig',
            [
                'form' => $form->createView(),
                'note' => $note,
            ]
        );
    }

    /**
     * Delete action.
     *
     * @param \Symfony\Component\HttpFoundation\Request $request HTTP request
     * @param \App\Entity\Note                          $note    Note entity
     *
     * @return \Symfony\Component\HttpFoundation\Response HTTP response
     *
     * @throws \Doctrine\ORM\ORMException
     * @throws \Doctrine\ORM\OptimisticLockException
     *
     * @Route(
     *     "/{id}/delete",
     *     methods={"GET", "DELETE"},
     *     requirements={"id": "[1-9]\d*"},
     *     name="note_delete",
     * )
     *
     * @Security(
     *     "is_granted('ROLE_ADMIN') or is_granted('DELETE', note)"
     * )
     */
    public function delete(Request $request, Note $note): Response
    {
        $form = $this->createForm(FormType::class, $note, ['method' => 'DELETE']);
        $form->handleRequest($request);

        if ($request->isMethod('DELETE') && !$form->isSubmitted()) {
            $form->submit($request->request->get($form->getName()));
        }

        if ($form->isSubmitted() && $form->isValid()) {
            $this->noteService->delete($note);
            $this->addFlash('success', 'message_note_deleted_successfully');

            return $this->redirectToRoute('note_index');
        }

        return $this->render(
            'note/delete.html.twig',
            [
                'form' => $form->createView(),
                'note' => $note,
            ]
        );
    }
}

app/templates/note/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'title_note_create'|trans }}
{% endblock %}

{% block body %}
    <h1>{{ 'title_note_create'|trans }}</h1>
    {{ form_start(form, { method: 'POST', action: url('note_create') }) }}
    {{ form_widget(form) }}
    <div class="form-group row float-sm-right">
        <input type="submit" value="{{ 'action_create'|trans }}" class="btn btn-primary" />
    </div>
    <div class="form-group row float-sm-left">
        <a href="{{ url('note_index') }}" class="btn btn-link">
            {{ 'action_back_to_list'|trans }}
        </a>
    </div>
    {{ form_end(form) }}
{% endblock %}

app/templates/note/delete.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'title_note_delete'|trans({'%id%': note.id|default('')}) }}
{% endblock %}

{% block body %}
    <h1>{{ 'title_note_delete'|trans({'%id%': note.id|default('')}) }}</h1>
    {{ form_start(form, { method: 'DELETE', action: url('note_delete', {id: note.id}) }) }}
    {{ form_widget(form) }}
    <div class="form-group row float-sm-right">
        <input type="submit" value="{{ 'action_save'|trans }}" class="btn btn-primary" />
    </div>
    <div class="form-group row float-sm-left">
        <a href="{{ url('note_index') }}" class="btn btn-link">
            {{ 'action_back_to_list'|trans }}
        </a>
    </div>
    {{ form_end(form) }}
{% endblock %}

app/templates/note/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'title_note_edit'|trans({'%id': note.id|default('')}) }}
{% endblock %}

{% block body %}
    <h1>{{ 'title_note_edit'|trans({'%id': note.id|default('')}) }}</h1>
    {{ form_start(form, { method: 'PUT', action: url('note_edit', {id:note.id}) }) }}
    {{ form_widget(form) }}
    <div class="form-group row float-sm-right">
        <input type="submit" value="{{ 'action_save'|trans }}" class="btn btn-primary" />
    </div>
    <div class="form-group row float-sm-left">
        <a href="{{ url('note_index') }}" class="btn btn-link">
            {{ 'action_back_to_list'|trans }}
        </a>
    </div>
    {{ form_end(form) }}
{% endblock %}

app/templates/note/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'title_note_list'|trans }}
{% endblock %}

{% block body %}
    <h1>{{ 'title_note_list'|trans }}</h1>
    {% if pagination is defined and pagination.items|length %}

        <div class="navigation text-center">
            {{ knp_pagination_render(pagination) }}
        </div>

        <table class="table table-striped">
            <thead>
            <tr>
                <th>{{ knp_pagination_sortable(pagination, 'label_id'|trans, 'note.id') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'label_updated_at'|trans, 'note.updatedAt') }}</th>
                {% if is_granted("ROLE_ADMIN") %}
                    <th>{{ 'label_author'|trans }}</th>
                {% endif %}
                <th>{{ knp_pagination_sortable(pagination, 'label_title'|trans, 'note.title') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'label_category'|trans, 'category.title') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'label_tags'|trans, 'tag.name') }}</th>
                <th>{{ 'label_actions'|trans }}</th>
            </tr>
            </thead>
            <tbody>
            {% for note in pagination.items %}
                <tr>
                    <td>{{ note.id }}</td>
                    <td>{{ note.updatedAt|date('d/m/Y') }}</td>
                    {% if is_granted("ROLE_ADMIN") %}
                        <td>{{ note.author.email }}</td>
                    {%  endif %}
                    <td>{{ note.title }}</td>
                    <td>
                        <a href="{{ url('note_index', {'filters' : {'category' : note.category.id}}) }}" title="{{ note.category.title }}">
                            {{ note.category.title }}
                        </a>
                    </td>
                    <td>
                        {% if note.tags is defined and note.tags|length %}
                            {% for tag in note.tags %}
                                <a href="{{ url('note_index', {'filters' : {'tag' : tag.id}}) }}" title="{{ tag.name }}">
                                    {{ tag.name }}
                                </a>
                            {% endfor %}
                        {% else %}
                            &nbsp;
                        {% endif %}
                    </td>
                    <td>
                        <a href="{{ url('note_show', {id: note.id}) }}" title="{{ 'action_view'|trans }}">
                            {{ 'action_view'|trans }}
                        </a>

                        <a href="{{ url('note_edit', {id: note.id}) }}" title="{{ 'action_edit'|trans }}">
                            {{ 'action_edit'|trans }}
                        </a>
                        <a href="{{ url('note_delete', {id: note.id}) }}" title="{{ 'action_delete'|trans }}">
                            {{ 'action_delete'|trans }}
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <div class="navigation text-center">
            {{ knp_pagination_render(pagination) }}
        </div>

    {% else %}
        {% include 'default/_single_flash_message.html.twig' with{
            type: 'warning',
            message: 'message_empty_list'|trans
        } %}
    {% endif %}
{% endblock %}

app/templates/note/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'title_note_details'|trans({'%id%': note.id|default('')}) }}
{% endblock %}

{% block body %}
    <h1>{{ 'title_note_details'|trans({'%id%': note.id|default('')}) }}</h1>
    {% if note is defined and note|length %}
        <dl class="dl-horizontal">
            <dt>{{ 'label_id'|trans }}</dt>
            <dd>{{ note.id }}</dd>
            {% if is_granted("ROLE_ADMIN") %}
                <dt>{{ 'label_author'|trans }}</dt>
                <dd>{{ note.author.email }}</dd>
            {%  endif %}
            <dt>{{ 'label_created_at'|trans }}</dt>
            <dd>{{ note.createdAt|date('Y/m/d') }}</dd>
            <dt>{{ 'label_updated_at'|trans }}</dt>
            <dd>{{ note.updatedAt|date('Y/m/d') }}</dd>
            <dt>{{ 'label_title'|trans }}</dt>
            <dd>{{  note.title }}</dd>
            <dt>{{ 'label_content'|trans }}</dt>
            <dd>{{  note.content }}</dd>
        </dl>
        <p>
            <a href="{{ url('note_index') }}" title="{{ 'action_back_to_list'|trans }}">
                {{ 'action_back_to_list'|trans }}
            </a>
        </p>
    {% else %}
        <p>
            {{ 'message_item_not_found'|trans }}
        </p>
    {% endif %}
{% endblock %}