app/src/Entity/Task.php
<?php
/**
 * Task entity.
 */

namespace App\Entity;

use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class Task.
 *
 * @ORM\Entity(repositoryClass="App\Repository\TaskRepository")
 * @ORM\Table(name="tasks")
 */
class Task
{
    /**
     * Primary key.
     *
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * Created at.
     *
     * @var DateTimeInterface
     *
     * @ORM\Column(type="datetime")
     *
     * @Assert\DateTime
     *
     * @Gedmo\Timestampable(on="create")
     */
    private $createdAt;

    /**
     * Updated at.
     *
     * @var DateTimeInterface
     *
     * @ORM\Column(type="datetime")
     *
     * @Assert\DateTime
     *
     * @Gedmo\Timestampable(on="update")
     */
    private $updatedAt;

    /**
     * Title.
     *
     * @var string
     *
     * @ORM\Column(
     *     type="string",
     *     length=255,
     * )
     */
    private $title;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="tasks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\ManyToMany(targetEntity=Tag::class, inversedBy="tasks")
     */
    private $tags;

    /**
     * Author.
     *
     * @var \App\Entity\User
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * Comments.
     *
     * @var array
     *
     * @ORM\OneToMany(
     *     targetEntity=Comment::class,
     *     mappedBy="task",
     *     orphanRemoval=true
     * )
     *
     * @Assert\All({
     * @Assert\Type(type="App\Entity\Comment")
     * })
     */
    private $comment;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->comment = new ArrayCollection();
    }

    /**
     * Getter for Id.
     *
     * @return int|null Result
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Getter for Created At.
     *
     * @return \DateTimeInterface|null Created at
     */
    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->createdAt;
    }

    /**
     * Setter for Created at.
     *
     * @param \DateTimeInterface $createdAt Created at
     */
    public function setCreatedAt(DateTimeInterface $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Getter for Updated at.
     *
     * @return \DateTimeInterface|null Updated at
     */
    public function getUpdatedAt(): ?DateTimeInterface
    {
        return $this->updatedAt;
    }

    /**
     * Setter for Updated at.
     *
     * @param \DateTimeInterface $updatedAt Updated at
     */
    public function setUpdatedAt(DateTimeInterface $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * Getter for Title.
     *
     * @return string|null Title
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * Setter for Title.
     *
     * @param string $title Title
     */
    public function setTitle(string $title): void
    {
        $this->title = $title;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * Getter for comment.
     *
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comment;
    }

    /**
     * Add comment.
     *
     * @return $this
     */
    public function addComment(Comment $comment): self
    {
        if (!$this->comment->contains($comment)) {
            $this->comment[] = $comment;
            $comment->setTask($this);
        }

        return $this;
    }

    /**
     * Remove comment.
     *
     * @return $this
     */
    public function removeComment(Comment $comment): self
    {
        if ($this->comment->contains($comment)) {
            $this->comment->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getTask() === $this) {
                $comment->setTask(null);
            }
        }

        return $this;
    }

    /* public function getCategory(): ?Category
     {
         return $this->category;
     }

     public function setCategory(?Category $category): self
     {
         $this->category = $category;

         return $this;
     }

     */
}

app/src/Form/TaskType.php
<?php
/**
 * Task type.
 */

namespace App\Form;

use App\Entity\Category;
use App\Entity\Task;
use App\Form\DataTransformer\TagsDataTransformer;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class TaskType.
 */
class TaskType extends AbstractType
{
    /**
     * Tags data transformer.
     *
     * @var \App\Form\DataTransformer\TagsDataTransformer
     */
    private $tagsDataTransformer;

    /**
     * TaskType constructor.
     *
     * @param \App\Form\DataTransformer\TagsDataTransformer $tagsDataTransformer Tags data transformer
     */
    public function __construct(TagsDataTransformer $tagsDataTransformer)
    {
        $this->tagsDataTransformer = $tagsDataTransformer;
    }

    /**
     * Builds the form.
     *
     * This method is called for each type in the hierarchy starting from the
     * top most type. Type extensions can further modify the form.
     *
     * @see FormTypeExtensionInterface::buildForm()
     *
     * @param \Symfony\Component\Form\FormBuilderInterface $builder The form builder
     * @param array                                        $options The options
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add(
            'title',
            TextType::class,
            [
                'label' => 'label_title',
                'required' => true,
                'attr' => ['max_length' => 64],
            ]
        );
        $builder->add(
            'category',
            EntityType::class,
            [
                'class' => Category::class,
                'choice_label' => function ($category) {
                    return $category->getTitle();
                },
                'label' => 'label_category',
                'placeholder' => 'label_none',
                'required' => true,
            ]
        );
        $builder->add(
            'tags',
            TextType::class,
            [
                'label' => 'label_tag',
                'required' => false,
                'attr' => ['max_length' => 128],
            ]
        );
        $builder->get('tags')->addModelTransformer(
            $this->tagsDataTransformer
        );
    }

    /**
     * Configures the options for this type.
     *
     * @param \Symfony\Component\OptionsResolver\OptionsResolver $resolver The resolver for the options
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults(['data_class' => Task::class]);
    }

    /**
     * Returns the prefix of the template block name for this type.
     *
     * The block prefix defaults to the underscored short class name with
     * the "Type" suffix removed (e.g. "UserProfileType" => "user_profile").
     *
     * @return string The prefix of the template block name
     */
    public function getBlockPrefix(): string
    {
        return 'task';
    }
}

app/src/Controller/TaskController.php
<?php
/**
 * Task controller.
 */

namespace App\Controller;

use App\Entity\Task;
use App\Form\TaskType;
use App\Service\TaskService;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class TaskController.
 *
 * @Route("/")
 */
class TaskController extends AbstractController
{
    /**
     * Task service.
     *
     * @var \App\Service\TaskService
     */
    private $taskService;

    /**
     * TaskController constructor.
     *
     * @param \App\Service\TaskService $taskService Task service
     */
    public function __construct(TaskService $taskService)
    {
        $this->taskService = $taskService;
    }

    /**
     * Index action.
     *
     * @param \Symfony\Component\HttpFoundation\Request $request HTTP request
     *
     * @return \Symfony\Component\HttpFoundation\Response HTTP response
     *
     * @Route(
     *     "/",
     *     name="task_index",
     * )
     */
    public function index(Request $request): Response
    {
        $pagination = $this->taskService->createPaginatedList(
            $request->query->getInt('page', 1),
            $this->getUser(),
            $request->query->getAlnum('filters', [])
        );

        return $this->render(
            'task/index.html.twig',
            ['pagination' => $pagination]
        );
    }

    /**
     * Show action.
     *
     * @param \App\Entity\Task $task Task entity
     *
     * @return \Symfony\Component\HttpFoundation\Response HTTP response
     *
     * @throws \Doctrine\ORM\ORMException
     * @throws \Doctrine\ORM\OptimisticLockException
     *
     * @Route(
     *     "/{id}",
     *     methods={"GET", "POST"},
     *     name="task_show",
     *     requirements={"id": "[1-9]\d*"},
     * )
     *
     * @Security(
     *     "is_granted('ROLE_ADMIN') or is_granted('VIEW', task)"
     * )
     */
    public function show(Task $task): Response
    {
        return $this->render(
            'task/show.html.twig',
            ['task' => $task]
        );
    }

    /**
     * Create action.
     *
     * @param \Symfony\Component\HttpFoundation\Request $request HTTP request
     *
     * @return \Symfony\Component\HttpFoundation\Response HTTP response
     *
     * @throws \Doctrine\ORM\ORMException
     * @throws \Doctrine\ORM\OptimisticLockException
     *
     * @Route(
     *     "/create",
     *     methods={"GET", "POST"},
     *     name="task_create",
     * )
     */
    public function create(Request $request): Response
    {
        $task = new Task();
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $task->setAuthor($this->getUser());
            $this->taskService->save($task);
            $this->addFlash('success', 'message_created_successfully');

            return $this->redirectToRoute('task_index');
        }

        return $this->render(
            'task/create.html.twig',
            ['form' => $form->createView()]
        );
    }

    /**
     * Edit action.
     *
     * @param \Symfony\Component\HttpFoundation\Request $request HTTP request
     * @param \App\Entity\Task                          $task    Task entity
     *
     * @return \Symfony\Component\HttpFoundation\Response HTTP response
     *
     * @throws \Doctrine\ORM\ORMException
     * @throws \Doctrine\ORM\OptimisticLockException
     *
     * @Route(
     *     "/{id}/edit",
     *     methods={"GET", "PUT"},
     *     requirements={"id": "[1-9]\d*"},
     *     name="task_edit",
     * )
     *
     * @Security(
     *     "is_granted('ROLE_ADMIN') or is_granted('EDIT', task)"
     * )
     */
    public function edit(Request $request, Task $task): Response
    {
        $form = $this->createForm(TaskType::class, $task, ['method' => 'PUT']);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->taskService->save($task);
            $task->setUpdatedAt(new \DateTime());
            $this->addFlash('success', 'message_updated_successfully');

            return $this->redirectToRoute('task_index');
        }

        return $this->render(
            'task/edit.html.twig',
            [
                'form' => $form->createView(),
                'task' => $task,
            ]
        );
    }

    /**
     * Delete action.
     *
     * @param \Symfony\Component\HttpFoundation\Request $request HTTP request
     * @param \App\Entity\Task                          $task    Task entity
     *
     * @return \Symfony\Component\HttpFoundation\Response HTTP response
     *
     * @throws \Doctrine\ORM\ORMException
     * @throws \Doctrine\ORM\OptimisticLockException
     *
     * @Route(
     *     "/{id}/delete",
     *     methods={"GET", "DELETE"},
     *     requirements={"id": "[1-9]\d*"},
     *     name="task_delete",
     * )
     *
     * @Security(
     *     "is_granted('ROLE_ADMIN') or is_granted('DELETE', task)"
     * )
     */
    public function delete(Request $request, Task $task): Response
    {
        $form = $this->createForm(FormType::class, $task, ['method' => 'DELETE']);
        $form->handleRequest($request);

        if ($request->isMethod('DELETE') && !$form->isSubmitted()) {
            $form->submit($request->request->get($form->getName()));
        }

        if ($form->isSubmitted() && $form->isValid()) {
            $this->taskService->delete($task);
            $this->addFlash('success', 'message_deleted_successfully');

            return $this->redirectToRoute('task_index');
        }

        return $this->render(
            'task/delete.html.twig',
            [
                'form' => $form->createView(),
                'task' => $task,
            ]
        );
    }
}

app/templates/task/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'title_task_create'|trans }}
{% endblock %}

{% block body %}
    <h1>{{ 'title_task_create'|trans }}</h1>
    {{ form_start(form, { method: 'POST', action: url('task_create') }) }}
    {{ form_widget(form) }}
    <div class="form-group row float-sm-right">
        <input type="submit" value="{{ 'action_save'|trans }}" class="btn btn-primary" />
    </div>
    <div class="form-group row float-sm-left">
        <a href="{{ url('task_index') }}" class="btn btn-link">
            {{ 'action_back_to_list'|trans }}
        </a>
    </div>
    {{ form_end(form) }}
{% endblock %}

app/templates/task/delete.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'title_task_delete'|trans({'%id%': task.id|default('')}) }}
{% endblock %}

{% block body %}
    <h1>{{ 'title_task_delete'|trans({'%id%': task.id|default('')}) }}</h1>
    {{ form_start(form, { method: 'DELETE', action: url('task_delete', {id: task.id}) }) }}
    {{ form_widget(form) }}
    <div class="form-group row float-sm-right">
        <input type="submit" value="{{ 'action_delete'|trans }}" class="btn btn-primary" />
    </div>
    <div class="form-group row float-sm-left">
        <a href="{{ url('task_index') }}" class="btn btn-link">
            {{ 'action_back_to_list'|trans }}
        </a>
    </div>
    {{ form_end(form) }}
{% endblock %}

app/templates/task/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'title_task_edit'|trans({'%id': task.id|default('')}) }}
{% endblock %}

{% block body %}
    <h1>{{ 'title_task_edit'|trans({'%id': task.id|default('')}) }}</h1>
    {{ form_start(form, { method: 'PUT', action: url('task_edit', {id:task.id}) }) }}
    {{ form_widget(form) }}
    <div class="form-group row float-sm-right">
        <input type="submit" value="{{ 'action_save'|trans }}" class="btn btn-primary" />
    </div>
    <div class="form-group row float-sm-left">
        <a href="{{ url('task_index') }}" class="btn btn-link">
            {{ 'action_back_to_list'|trans }}
        </a>
    </div>
    {{ form_end(form) }}
{% endblock %}

app/templates/task/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'title_task_list'|trans }}
{% endblock %}

{% block body %}
    <h1>{{ 'title_task_list'|trans }}</h1>
    {% if pagination is defined and pagination.items|length %}

        <div class="navigation text-center">
            {{ knp_pagination_render(pagination) }}
        </div>

        <table class="table table-striped">
            <thead>
            <tr>
                <th>{{ knp_pagination_sortable(pagination, 'label_id'|trans, 'task.id') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'label_created_at'|trans, 'task.createdAt') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'label_updated_at'|trans, 'task.updatedAt') }}</th>
                {% if is_granted("ROLE_ADMIN") %}
                    <th>{{ 'label_author'|trans }}</th>
                {% endif %}

                <th>{{ knp_pagination_sortable(pagination, 'label_title'|trans, 'task.title') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'label_category'|trans, 'category.title') }}</th>
                <th>{{ knp_pagination_sortable(pagination, 'label_tags'|trans, 'tag.name') }}</th>
                <th>{{ 'label_actions'|trans }}</th>
            </tr>
            </thead>
            <tbody>
            {% for task in pagination.items %}
                <tr>
                    <td>{{ task.id }}</td>
                    <td>{{ task.createdAt|date('d/m/Y') }}</td>
                    <td>{{ task.updatedAt|date('d/m/Y') }}</td>
                    {% if is_granted("ROLE_ADMIN") %}
                        <td>{{ task.author.email }}</td>
                    {%  endif %}
                    <td>{{ task.title }}</td>
                    <td>
                        <a href="{{ url('task_index', {'filters' : {'category' : task.category.id}}) }}" title="{{ task.category.title }}">
                            {{ task.category.title }}
                        </a>
                    </td>
                    <td>
                        {% if task.tags is defined and task.tags|length %}
                            {% for tag in task.tags %}
                                <a href="{{ url('task_index', {'filters' : {'tag' : tag.id}}) }}" title="{{ tag.name }}">
                                    {{ tag.name }}
                                </a>
                            {% endfor %}
                        {% else %}
                            &nbsp;
                        {% endif %}
                    </td>

                    <td>
                        {% if is_granted ('ROLE_ADMIN') or is_granted('VIEW', task) %}
                            <a href="{{ url('task_show', {id: task.id}) }}" title="{{ 'action_view'|trans }}">
                                {{ 'action_view'|trans }}
                            </a>
                        {% endif %}
                        {% if is_granted ('ROLE_ADMIN') or is_granted('EDIT', task) %}
                            <a href="{{ url('task_edit', {id: task.id}) }}" title="{{ 'action_edit'|trans }}">
                                {{ 'action_edit'|trans }}
                            </a>
                        {% endif %}
                        {% if is_granted ('ROLE_ADMIN') or is_granted('DELETE', task) %}
                            <a href="{{ url('task_delete', {id: task.id}) }}" title="{{ 'action_delete'|trans }}">
                                {{ 'action_delete'|trans }}
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <div class="navigation text-center">
            {{ knp_pagination_render(pagination) }}
        </div>

    {% else %}
        {% include 'default/_single_flash_message.html.twig' with{
            type: 'warning',
            message: 'message_empty_list'|trans
        } %}
    {% endif %}
{% endblock %}

app/templates/task/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'title_task_details'|trans({'%id%': task.id|default('')}) }}
{% endblock %}

{% block body %}
    <h1>{{ 'title_task_details'|trans({'%id%': task.id|default('')}) }}</h1>
    {% if task is defined and task|length %}
        <dl class="dl-horizontal">
            <dt>{{ 'label_id'|trans }}</dt>
            <dd>{{ task.id }}</dd>
            {% if is_granted("ROLE_ADMIN") %}
                <dt>{{ 'label_author'|trans }}</dt>
                <dd>{{ task.author.email }}</dd>
            {%  endif %}
            <dt>{{ 'label_created_at'|trans }}</dt>
            <dd>{{ task.createdAt|date('Y/m/d') }}</dd>
            <dt>{{ 'label_updated_at'|trans }}</dt>
            <dd>{{ task.updatedAt|date('Y/m/d') }}</dd>
            <dt>{{ 'label_title'|trans }}</dt>
            <dd>{{  task.title }}</dd>

        </dl>
        <br>
        <dt><h4>{{ 'label_comments'|trans }}</h4></dt>
        <dd>{%  for comment in task.comments %}
                <strong>{{ comment.createdAt|date('d.m.Y') }}</strong><br>
                {{ comment.content }}
                <br>
                <p>
                    <a href="{{ url('comment_delete', {'id': comment.id})}}" title="{{ 'action_delete'|trans }}" class="btn btn-info">
                        {{ 'action_delete'|trans }}
                    </a>
                </p>
            {% endfor %}
        </dd>
        </dl>
        <div>
            <br>
            <h5>{{ 'add_comment'|trans }}</h5>

            {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
                <p>
                    <a href="{{ url('comment_create', {'id': task.id}) }}" title="{{ 'action_create'|trans }}" class="btn btn-info">
                        {{ 'action_create'|trans }}
                    </a>
                </p>
                <p>
                    <a href="{{ url('task_index') }}" title="{{ 'action_back_to_list'|trans }}" class="btn btn-info">
                        {{ 'action_back_to_list'|trans }}
                    </a>
                </p>
            {% else %}
                <p>
                    {{ 'message_item_not_found'|trans }}
                </p>
            {% endif %}
        </div>
    {% endif %}

{% endblock %}